name: ${project.name}
main: de.guildcraft.guildConomy.GCPlugin
version: ${project.version}
author: sirkarpfen, madroxxlino
database: true
description The second most important plugin for guild-craft.de
depend: [Votifier]
commands:
    eco: